adding optioin for excel conditional formating [sc-161134]
dataiku/dss-plugin-sendmail pull request #10
Opened 2024-02-16 17:10 UTC by liamlynch-data

Pretty straightforward 
(assuming people are happy with the DSS backend changes for this)

2024-02-19 08:32 UTC, liamlynch-data commented
I just thought - probably we don't want the new option to show unless we're on a version of DSS that supports it. I will try to add something to do that now.

2024-02-19 13:33 UTC, liamlynch-data commented
> I just thought - probably we don't want the new option to show unless we're on a version of DSS that supports it. I will try to add something to do that now.

Done in https://github.com/dataiku/dss-plugin-sendmail/pull/10/commits/1bc91fa2f89e76dae578cb7b94202f5d11d1aafa

2024-02-21 10:05 UTC, alexbourret approved these changes
All good !

2024-02-22 10:02 UTC, MayeulRousselet requested changes

2024-02-22 10:02 UTC, MayeulRousselet commented on resource/dynamic_form.py
> +def is_12_6_plus(dss_client):
Better to rename it to `support_messaging_channel_and_conditionnal_formatting`

2024-02-22 10:02 UTC, MayeulRousselet commented on python-lib/dku_attachment_handling.py
> +        format_params = {"applyColoring": (apply_coloring_excel and attachment_type == "excel_can_ac")}
`applyColoring` will be sent on DSS < 12.6 (not a big deal)

2024-02-22 16:49 UTC, MayeulRousselet reviewed
Tested it with attaching foreign dataset that have conditional formatting on the source:
- Expected: no CF is applied
- Actual: CF is applied.

this is due to an issue in the export (https://app.shortcut.com/dataiku/story/173249) not to be covered here so.

2024-02-27 07:55 UTC, liamlynch-data commented on resource/dynamic_form.py
> +def is_12_6_plus(dss_client):
Renamed [here](https://github.com/dataiku/dss-plugin-sendmail/pull/10/commits/052303cae4f8c86783dcd9c7359c7d255d622f48#diff-44f227161ef56923c43a70ade7493cd01df31e6e43d33fba892abba4021da9b4)

2024-02-27 07:56 UTC, liamlynch-data commented on python-lib/dku_attachment_handling.py
> +        format_params = {"applyColoring": (apply_coloring_excel and attachment_type == "excel_can_ac")}
Changed so only sends format_params where needed [here ](https://github.com/dataiku/dss-plugin-sendmail/pull/10/commits/052303cae4f8c86783dcd9c7359c7d255d622f48#diff-e84ac22d39938fd532a4d10e767fc0e6f64cdc3b98225263cedcf204d6ff6865)

2024-03-01 13:49 UTC, MayeulRousselet approved these changes
LGTM thx for the changes

2024-03-04 09:49 UTC, merged