Add ability to export a dataset into html formatted with conditional formatting
dataiku/dss-plugin-sendmail pull request #12
Opened 2024-04-16 21:44 UTC by apichery

Need https://github.com/dataiku/dip/pull/28655 for it to work

2024-04-17 09:25 UTC, thomaswartel commented
@apichery it works very well, thanks a lot!

I think we should update the recipe.json to update the condition when to display the conditional formatting. Now, conditional formatting is no longer related to Excel files only. One can apply a conditional format in the body + Excel independently 👍 

https://github.com/dataiku/dss-plugin-sendmail/assets/105646698/45068ec3-7df2-46f4-ab3d-43404eaaea48


`{
            "name": "apply_coloring_excel",
            "label" : "Apply conditional formatting",
            "description" : "Color cells by rules, when applicable in the HTML body. Will also be applied when attachment format is Excel.",
            "type": "BOOLEAN",
            "visibilityCondition" : "(model.body_format == 'html') || (model.attachment_type == 'excel_can_ac')"
        }`

2024-04-17 17:35 UTC, liamlynch-data approved these changes
Looks fine - just needed to bump the version in the JSON.
Also will implement Thomas's suggestion in another commit

2024-04-17 17:35 UTC, liamlynch-data commented on CHANGELOG.md
> +## [Version 1.0.1](https://github.com/dataiku/dss-plugin-sendmail/releases/tag/v1.0.1) - Feature release - 2024-04
We need to up the version number in the plugin json also

2024-04-17 17:35 UTC, liamlynch-data commented on CHANGELOG.md
> +## [Version 1.0.1](https://github.com/dataiku/dss-plugin-sendmail/releases/tag/v1.0.1) - Feature release - 2024-04
Done here https://github.com/dataiku/dss-plugin-sendmail/pull/12/commits/2ed8532b938a4cd078ee5812a3a74d678450db9b

2024-04-17 17:42 UTC, liamlynch-data requested changes
Actually not sure if the param to toggle the formating is being used (seems to be always on). I will fix it

2024-04-17 18:00 UTC, liamlynch-data commented
Here https://github.com/dataiku/dss-plugin-sendmail/pull/12/commits/7ac69c80ca70bb7df8d44a6d49c17d2a0de8d42b I
- implemented the suggestion of @thomaswartel 
- made the parameter control whether formating applied, for HTML as well as excel

(Another choice would be that the formatting is always applied for the HTML output and the toggle only applies for excel -if that's what we really want, revert this commit as that was how it behaved before)

Note - I also tested on old DSS version (12.5.2), and range of python versions (3.6, 3.9, 3.11)

2024-04-17 18:00 UTC, liamlynch-data approved these changes

2024-04-18 09:15 UTC, liamlynch-data commented
- Added send_no_attachments option  and changed defaults behaviour for attachments 
- Added some more section headings
- Conditional formating on by default (if excel attached or HTML output used)

As agreed with @thomaswartel  and @MayeulRousselet

2024-04-18 15:05 UTC, MayeulRousselet approved these changes
LGTM!

2024-04-18 15:05 UTC, MayeulRousselet commented on python-lib/dku_attachment_handling.py
> +        if hasattr(attachment_ds.__class__, "to_html") and callable(getattr(attachment_ds.__class__, "to_html")):
Nitpick: Extract this check in a method `supports_dataset_to_html`

2024-04-19 08:21 UTC, liamlynch-data commented
I will address the nitpick of @MayeulRousselet then merge this PR - then move on to the [subsequent ticket](https://app.shortcut.com/dataiku/story/180121/plugin-migration-update-issue-existing-recipes-on-dss-12-6-with-excel-as-an-attachement-will-show-nothing-selecting-when) - unless objections

2024-04-19 11:57 UTC, liamlynch-data commented on python-lib/dku_attachment_handling.py
> +        if hasattr(attachment_ds.__class__, "to_html") and callable(getattr(attachment_ds.__class__, "to_html")):
Addressed [here](https://github.com/dataiku/dss-plugin-sendmail/pull/12/commits/148ad97f37abbf20283483efab3dfaca8d1e5a72)

2024-04-19 11:59 UTC, merged